# generated by datamodel-codegen:
#   filename:  swagger.yaml
#   timestamp: 2026-02-14T14:31:14+00:00

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    condecimal,
    conint,
)


class ErrorStatusCode(Enum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    INTERNAL = "INTERNAL"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: ErrorStatusCode
    errors: list[str]


class ChainTokenStatic(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    methodName: str = Field(..., description="Payment method name (token + chain)")
    address: str = Field(..., description="Payment address")


class StaticWallet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID = Field(..., description="Wallet id")
    orderId: str = Field(
        ..., description="ID in the client's system (specified when creating a wallet)"
    )
    addresses: list[ChainTokenStatic] = Field(
        ..., description="Wallet addresses for payment"
    )


class UUIDModel(RootModel[UUID]):
    root: UUID


class CreateStaticWalletRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str = Field(..., description="ID in the client's system")


class Rate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    rate: str


class PaymentMethod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    methodName: str = Field(..., description="Payment method name (token + chain)")
    icon: str = Field(..., description="Payment method icon")


class PaymentMethods(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    paymentMethods: list[PaymentMethod]


class InvoiceStatus(Enum):
    WAITING_SELECTION = "WAITING_SELECTION"
    WAITING_PAYMENT = "WAITING_PAYMENT"
    COMPLETE = "COMPLETE"
    EXPIRED = "EXPIRED"
    OVER_PAID = "OVER_PAID"
    UNDER_PAID = "UNDER_PAID"


class LastTransaction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chain: str = Field(..., description="Chain name")
    txid: str = Field(..., description="Transaction Hash")


class PaymentDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    address: str | None = Field(None, description="Payment address")
    amount: Decimal | None = Field(
        None, description="Expected payment amount in tokens"
    )


class Invoice(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID = Field(..., description="Invoice id")
    orderId: str = Field(
        ...,
        description="ID in the client's system (specified when creating an invoice)",
    )
    description: str | None = Field(
        None, description="Description shown on the payment page"
    )
    amount: Decimal | None = Field(
        None, description="Original order amount in USD (excluding service fee)"
    )
    paymentAmount: Decimal | None = Field(
        None, description="Amount to pay in USD (excluding service fee if feeIncluded)"
    )
    paidAmount: Decimal = Field(
        ..., description="Total amount actually paid by the customer in USD"
    )
    feeIncluded: bool = Field(
        ...,
        description="If true, the service fee is added to paymentDetails.amount (paid by customer)",
    )
    accuracy: Decimal = Field(
        ...,
        description="Allowed payment deviation (0 to 0.05). If within range, status is COMPLETE",
    )
    feeRate: Decimal = Field(
        ..., description="Service fee fraction (e.g., 0.02 for 2%)"
    )
    expectedMerchantAmount: Decimal = Field(
        ..., description="Expected credit to merchant balance if paid 100%"
    )
    merchantPaidAmount: Decimal = Field(
        ...,
        description="Actual amount already credited to merchant balance (paidAmount minus fee)",
    )
    createdAt: AwareDatetime = Field(..., description="ISO 8601 creation date")
    expiredAt: AwareDatetime = Field(..., description="ISO 8601 expiration date")
    originalExpiredAt: AwareDatetime | None = Field(
        None, description="Recorded original expiration date if prolonged"
    )
    canceledAt: AwareDatetime | None = Field(
        None, description="ISO 8601 cancellation date"
    )
    status: InvoiceStatus = Field(..., description="Current invoice status")
    url: AnyUrl = Field(..., description="Public payment page link")
    urlSuccess: AnyUrl | None = Field(
        None, description="Redirect URL after successful payment"
    )
    urlReturn: AnyUrl | None = Field(
        None, description="Redirect URL after failure (canceled or expired)"
    )
    supportLink: AnyUrl | None = Field(
        None, description="Merchant's support contact link"
    )
    lastTransaction: LastTransaction | None = Field(
        None, description="Info about the most recent incoming transaction"
    )
    paymentDetails: PaymentDetails | None = Field(
        None,
        description="Information about the selected payment method and the amount to be paid.",
    )


class ChainToken(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")


class CreateInvoiceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    orderId: str = Field(..., description="ID in the client's system")
    description: str | None = Field(
        None, description="Description, shown on the payment page"
    )
    amount: (
        condecimal(ge=0.01000000000000000020816681711721685132943093776702880859375)
        | None
    ) = Field(
        None,
        description="Invoice amount in USD. If omitted, any payment amount will result in COMPLETE status",
    )
    feeIncluded: bool | None = Field(
        False,
        description="If the option is enabled, the service fee will be added to the amount.",
    )
    accuracy: (
        condecimal(ge=0, le=0.05000000000000000277555756156289135105907917022705078125)
        | None
    ) = Field(
        "0",
        description="What deviation from amount should still be marked COMPLETE. From 0 to 0.05 where 0.05 is 5%",
    )
    urlSuccess: AnyUrl | None = Field(
        None, description="Redirect after successful payment"
    )
    urlReturn: AnyUrl | None = Field(
        None, description="Redirect after failure (canceled or expired)"
    )
    chainToken: ChainToken | None = Field(None, description="Selected chain and token")


class PatchInvoiceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: Decimal | None = Field(
        None,
        description="Invoice amount, can only be set if not specified during creation",
    )
    chainToken: ChainToken | None = Field(
        None,
        description="Chain and token, can only be set if not specified during creation",
    )


class Invoices(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invoices: list[Invoice] = Field(..., description="Requested invoices")
    totalCount: int = Field(
        ..., description="How many invoices in total (for pagination)"
    )


class GetHistoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fromDate: AwareDatetime = Field(
        ..., description="Start date for filtering in ISO 8601 format"
    )
    toDate: AwareDatetime | None = Field(
        None, description="End date for filtering in ISO 8601 format"
    )
    limit: conint(le=1000) | None = Field(
        1000, description="Maximum number of items to output. No more than 1000."
    )
    notNotified: bool | None = Field(
        False,
        description="If specified, will return notifications that have not yet been acknowledged.",
    )


class StaticWalletNotification(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID = Field(..., description="Wallet id")
    orderId: str = Field(
        ..., description="ID in the client's system (specified when creating a wallet)"
    )


class Transaction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    txid: str = Field(..., description="Transaction hash")
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    value: Decimal = Field(..., description="Amount in tokens")
    usd: Decimal = Field(
        ..., description="Amount in USD, before deducting the commission"
    )
    fee: Decimal = Field(..., description="Service fee in USD")
    wallet: StaticWalletNotification | None = Field(None, description="Wallet info")
    createdAt: AwareDatetime = Field(
        ..., description="Payment processing date in ISO 8601 format"
    )
    blockCreatedAt: AwareDatetime = Field(
        ..., description="Date of funds sent in ISO 8601 format"
    )
    merchantAmount: Decimal = Field(
        ...,
        description="Amount to be credited to the merchant, after deducting the commission",
    )
    id: UUID = Field(..., description="Transaction id")


class Transactions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    transactions: list[Transaction] = Field(..., description="Requested transactions")
    totalCount: int = Field(
        ..., description="How many transactions in total (for pagination)"
    )
