# generated by datamodel-codegen

from __future__ import annotations
from enum import Enum
from typing import Annotated
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field
from uuid import UUID
from decimal import Decimal


class ErrorStatusCode(str, Enum):
    invalid_argument = "INVALID_ARGUMENT"
    not_found = "NOT_FOUND"
    already_exists = "ALREADY_EXISTS"
    internal = "INTERNAL"
    unauthenticated = "UNAUTHENTICATED"
    permission_denied = "PERMISSION_DENIED"


class ErrorResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")
    code: ErrorStatusCode
    errors: list[str]


class ChainTokenStatic(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    method_name: str = Field(
        ..., alias="methodName", description="Payment method name (token + chain)"
    )
    address: str = Field(..., description="Payment address")


class StaticWallet(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: UUID = Field(..., description="Wallet id")
    order_id: str = Field(
        ...,
        alias="orderId",
        description="ID in the client's system (specified when creating a wallet)",
    )
    addresses: list[ChainTokenStatic] = Field(
        ..., description="Wallet addresses for payment"
    )


class CreateStaticWalletRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    order_id: str = Field(..., alias="orderId", description="ID in the client's system")


class Rate(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str
    rate: str


class PaymentMethod(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    method_name: str = Field(
        ..., alias="methodName", description="Payment method name (token + chain)"
    )
    icon: str = Field(..., description="Payment method icon")
    chain_icon: str = Field(..., alias="chainIcon", description="Chain icon")
    token_icon: str = Field(..., alias="tokenIcon", description="Token icon")


class PaymentMethods(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    payment_methods: list[PaymentMethod] = Field(..., alias="paymentMethods")


class InvoiceStatus(str, Enum):
    waiting_selection = "WAITING_SELECTION"
    waiting_payment = "WAITING_PAYMENT"
    complete = "COMPLETE"
    expired = "EXPIRED"
    over_paid = "OVER_PAID"
    under_paid = "UNDER_PAID"


class LastTransaction(BaseModel):
    model_config = ConfigDict(extra="forbid")
    chain: str = Field(..., description="Chain name")
    txid: str = Field(..., description="Transaction Hash")


class PaymentDetails(BaseModel):
    model_config = ConfigDict(extra="forbid")
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    address: str | None = Field(None, description="Payment address")
    amount: Decimal | None = Field(
        None, description="Expected payment amount in tokens"
    )


class Invoice(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: UUID = Field(..., description="Invoice id")
    order_id: str = Field(
        ...,
        alias="orderId",
        description="ID in the client's system (specified when creating an invoice)",
    )
    merchant_name: str = Field(..., alias="merchantName", description="Merchant's name")
    amount: Decimal | None = Field(
        None, description="Original order amount in USD (excluding service fee)"
    )
    payment_amount: Decimal | None = Field(
        None,
        alias="paymentAmount",
        description="Amount to pay in USD (excluding service fee if feeIncluded)",
    )
    paid_amount: Decimal = Field(
        ...,
        alias="paidAmount",
        description="Total amount actually paid by the customer in USD",
    )
    fee_included: bool = Field(
        ...,
        alias="feeIncluded",
        description="If true, the service fee is added to paymentDetails.amount (paid by customer)",
    )
    accuracy: Annotated[Decimal, Field(ge=Decimal("0"), le=Decimal("0.05"))] = Field(
        ...,
        description="Allowed payment deviation (0 to 0.05). If within range, status is COMPLETE",
    )
    fee_rate: Decimal = Field(
        ...,
        alias="feeRate",
        description="Service fee fraction (e.g., 0.02 for 2%)",
    )
    expected_merchant_amount: Decimal = Field(
        ...,
        alias="expectedMerchantAmount",
        description="Expected credit to merchant balance if paid 100%",
    )
    merchant_paid_amount: Decimal = Field(
        ...,
        alias="merchantPaidAmount",
        description="Actual amount already credited to merchant balance (paidAmount minus fee)",
    )
    created_at: AwareDatetime = Field(
        ..., alias="createdAt", description="ISO 8601 creation date"
    )
    expired_at: AwareDatetime = Field(
        ..., alias="expiredAt", description="ISO 8601 expiration date"
    )
    original_expired_at: AwareDatetime | None = Field(
        None,
        alias="originalExpiredAt",
        description="Recorded original expiration date if prolonged",
    )
    canceled_at: AwareDatetime | None = Field(
        None,
        alias="canceledAt",
        description="ISO 8601 cancellation date",
    )
    status: InvoiceStatus = Field(..., description="Current invoice status")
    url: AnyUrl = Field(..., description="Public payment page link")
    url_success: AnyUrl | None = Field(
        None, alias="urlSuccess", description="Redirect URL after successful payment"
    )
    url_return: AnyUrl | None = Field(
        None,
        alias="urlReturn",
        description="Redirect URL after failure (canceled or expired)",
    )
    support_link: AnyUrl | None = Field(
        None, alias="supportLink", description="Merchant's support contact link"
    )
    last_transaction: LastTransaction | None = Field(
        None,
        alias="lastTransaction",
        description="Info about the most recent incoming transaction",
    )
    payment_details: PaymentDetails | None = Field(
        None,
        alias="paymentDetails",
        description="Information about the selected payment method and the amount to be paid.",
    )


class ChainToken(BaseModel):
    model_config = ConfigDict(extra="forbid")
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")


class CreateInvoiceRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    order_id: str = Field(..., alias="orderId", description="ID in the client's system")
    amount: Annotated[Decimal, Field(ge=Decimal("0.01"))] | None = Field(
        None,
        description="Invoice amount in USD. If omitted, any payment amount will result in COMPLETE status",
    )
    fee_included: bool | None = Field(
        False,
        alias="feeIncluded",
        description="If the option is enabled, the service fee will be added to the amount.",
    )
    accuracy: Annotated[Decimal, Field(ge=Decimal("0"), le=Decimal("0.05"))] | None = (
        Field(
            "0",
            description="What deviation from amount should still be marked COMPLETE. From 0 to 0.05 where 0.05 is 5%",
        )
    )
    url_success: AnyUrl | None = Field(
        None, alias="urlSuccess", description="Redirect after successful payment"
    )
    url_return: AnyUrl | None = Field(
        None,
        alias="urlReturn",
        description="Redirect after failure (canceled or expired)",
    )
    chain_token: ChainToken | None = Field(
        None, alias="chainToken", description="Selected chain and token"
    )


class PatchInvoiceRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    amount: Decimal | None = Field(
        None,
        description="Invoice amount, can only be set if not specified during creation",
    )
    chain_token: ChainToken | None = Field(
        None,
        alias="chainToken",
        description="Chain and token, can only be set if not specified during creation",
    )


class Invoices(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    invoices: list[Invoice] = Field(..., description="Requested invoices")
    total_count: int = Field(
        ...,
        alias="totalCount",
        description="How many invoices in total (for pagination)",
    )


class GetHistoryRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    from_date: AwareDatetime = Field(
        ..., alias="fromDate", description="Start date for filtering in ISO 8601 format"
    )
    to_date: AwareDatetime | None = Field(
        None, alias="toDate", description="End date for filtering in ISO 8601 format"
    )
    limit: Annotated[int, Field(le=1000)] | None = Field(
        1000, description="Maximum number of items to output. No more than 1000."
    )
    not_notified: bool | None = Field(
        False,
        alias="notNotified",
        description="If specified, will return notifications that have not yet been acknowledged.",
    )


class StaticWalletNotification(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: UUID = Field(..., description="Wallet id")
    order_id: str = Field(
        ...,
        alias="orderId",
        description="ID in the client's system (specified when creating a wallet)",
    )


class Transaction(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    txid: str = Field(..., description="Transaction hash")
    chain: str = Field(..., description="Chain name")
    token: str = Field(..., description="Token name")
    value: Decimal = Field(..., description="Amount in tokens")
    usd: Decimal = Field(
        ..., description="Amount in USD, before deducting the commission"
    )
    fee: Decimal = Field(..., description="Service fee in USD")
    wallet: StaticWalletNotification | None = Field(None, description="Wallet info")
    created_at: AwareDatetime = Field(
        ..., alias="createdAt", description="Payment processing date in ISO 8601 format"
    )
    block_created_at: AwareDatetime = Field(
        ..., alias="blockCreatedAt", description="Date of funds sent in ISO 8601 format"
    )
    merchant_amount: Decimal = Field(
        ...,
        alias="merchantAmount",
        description="Amount to be credited to the merchant, after deducting the commission",
    )
    id: UUID = Field(..., description="Transaction id")


class Transactions(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    transactions: list[Transaction] = Field(..., description="Requested transactions")
    total_count: int = Field(
        ...,
        alias="totalCount",
        description="How many transactions in total (for pagination)",
    )
